### ISSUE TITLE
'FBSDKCoreKit/FBSDKCoreKit.h' file not found after updating plugin to V6.0.0

### ISSUE THREAD

**Issue by hellkith** [jeduan/cordova-plugin-facebook4#795]
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

This plugin has always worked perfectly for me on iOS. However since the changes for the pods manager, it doesn't work when I open the project in xCode and the build command fails.

When I run the following command: ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0" command it throws an error when it is done.
Stating that the CompileC for "FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler" has failed. (Removed the lengthy file path for readability)

if I then open the project in xCode and build the app it fails with the error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found

I did check and see if cocoapods was installed and I updated it just incase it could have been due to an outdated version.

**Plugin version, OS, devices, etc**

plugin version: 6.0.0
Ionic version: 4.1.0
Cordova version: 9.0
cordova-ios version: 4.5.5

**Comment by peterpeterparker** [comment]
Which file did you open in Xcode?

See [documentation](https://github.com/jeduan/cordova-plugin-facebook4/tree/master/docs/ios) 

> If building your project in Xcode, you need to open YourProject.xcworkspace (not YourProject.xcodeproj) so both your Cordova app project and the Pods project will be loaded into Xcode.

**Comment by hellkith** [comment]
I did open the .xcworkspace file. Seeing I have Firebase implemented and for that I need to open it with the .xcworkspace file aswell.

**Comment by peterpeterparker** [comment]
Maybe because of cordova-ios 4.x ?

I, and I guess others who reported it is all good, tested with iOS >= v5

**Comment by peterpeterparker** [comment]
Also another reported something similar to `'FBSDKCoreKit/FBSDKCoreKit.h' file not found` (not sure it was in Xcode) which he/she solved removing and adding cleanly the plugin again

**Comment by hellkith** [comment]
I'll give it a try with the newer Cordova iOS (it was kept at a lower version due to either this plugin or another plugin not working correctly with iOS >= 5).
If it still doesn't work, I'll let you know.

**Comment by peterpeterparker** [comment]
Coolio. Try first by removing cleanly the plugin and adding it again (before removing the platform)...you never know

**Comment by hellkith** [comment]
After a few hickups with cocoapods (somehow my repo was corrupted) it seems to be working with Cordova iOS >=5.
I do notice one difference during the installation proces with iOS 5 and 4.5.5.
With 4.5.5 it does **not** run the pod install during the plugin installation.
But even running it after the project has been build it will throw errors that the lockfile is missing and that the sandbox environment is out of sync.

So it might be good to make note of that for others that are running into this issue :)

**Comment by peterpeterparker** [comment]
@hellkith super cool, thx for the feedback, really happy to hear it worked out 👍 

sure make sense to add a notes, could you provide a PR?

**Comment by SirKnightDragoon** [comment]
> After a few hickups with cocoapods (somehow my repo was corrupted) it seems to be working with Cordova iOS >=5.
> I do notice one difference during the installation proces with iOS 5 and 4.5.5.
> With 4.5.5 it does **not** run the pod install during the plugin installation.
> But even running it after the project has been build it will throw errors that the lockfile is missing and that the sandbox environment is out of sync.
> 
> So it might be good to make note of that for others that are running into this issue :)

Ohh thanks! I updated cordova (9.0.0) and at the same time cordova ios to 5.0.1 and now my build is working :)

**Comment by tmdevde** [comment]
I get this Error on Phonegap Build with cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)  PhoneGap (iOS / Android / Windows when i want to build for iOS right now. A couple of Days ago everything was fine.

`In file included from /project/***/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m:13:
/project/***/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.h:13:9: fatal error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
#import <FBSDKCoreKit/FBSDKCoreKit.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.`

Any help here would be awesome.

**Comment by hellkith** [comment]
> I get this Error on Phonegap Build with cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0) PhoneGap (iOS / Android / Windows when i want to build for iOS right now. A couple of Days ago everything was fine.
> 
> `In file included from /project/***/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m:13: /project/***/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.h:13:9: fatal error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found #import <FBSDKCoreKit/FBSDKCoreKit.h> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 1 error generated.`
> 
> Any help here would be awesome.

I had the same error.
Make sure you are running Cordova V9 and that you are using Cordova ios 5.0.0 or higher.
To make sure you got cordova ios 5.0.0 you can pick the version by using cordova platform add ios@5.0.0

**Comment by tmdevde** [comment]
@hellkith thanks but i don't add platform, i'm just working with the config.xml since phonegap buils the app in the cloud. but as you can see in my forst post above it's using the correct versions.

**Comment by hellkith** [comment]
@tmdevde I've never worked with the phonegap cloud builder, so I don't know what it does/doesn't do. If both versions are correct, then it sounds like phonegap is not letting the pod install run. Seeing that pod install is what installs the frameworks.

Can you run commands via de phonegap build? Or is it solely upload a file and it does it's thing?

**Comment by tmdevde** [comment]
> Or is it solely upload a file and it does it's thing?

It's this. Unfurtanetly i can't run commands there because i have only one button to start a new build. PGB is getting the code from a github repo then and handles the build command by itself.

**Comment by hellkith** [comment]
@tmdevde I'm working with Ionic, so that does make things a little easier at times to debug/search what goes wrong.
Hope you hear back from PGB soon as I think they are the ones able to fix this for everyone that uses this plugin with PGB :)

**Comment by tmdevde** [comment]
working with ionic too but can't make iOS builds on windows. Maybe we can use their build service in the future.

Yes hope to hear from them too.

**Comment by ljudbane** [comment]
If you absolutely must use cordova ios < 5 the you can add the following lines to plugins/cordova-plugin-facebook4/plugin.xml inside <platform name="ios">:
`
<framework src="FBSDKCoreKit" type="podspec" spec="5.2.3" />
<framework src="FBSDKLoginKit" type="podspec" spec="5.2.3" />
<framework src="FBSDKShareKit" type="podspec" spec="5.2.3" />`

This will add the entries to ios platform's Podfile. Tested on cordova 6.5 and cordova_ios 4.5.5.

**Comment by peterpeterparker** [comment]
cool @ljudbane thx for the description for Cordova-ios < 5

in order to close this issue, should we add this to the ios installation guide?
and if yes could you provide a PR for that purpose?

**Comment by idanb007** [comment]
Hi 

Im having this issue also , I tried to remove and add iOS platform and it didn't fixed it :

my Ionic info is :
 @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.2.4
    Cordova Platforms  : android 7.0.0 ios 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 8.0.2 
    Node       : v10.16.3
    npm        : 6.9.0 
    OS         : macOS
    Xcode      : Xcode 10.3 Build version 10G8 

thanks for help

**Comment by bytenik** [comment]
I am also having the same issue. Its happening on my build server (CircleCI), which is rehydrating the plugins and platforms directory since they're not committed. It runs the following commands:

```
cordova platform add ios --verbose
cordova prepare ios --verbose
```

Followed by running _fastlane_ _gym_ to build.

**Comment by SteveKennedy** [comment]
I am using the latest of everything (as of 9/28) and still gets the "FBSDKCoreKit/FBSDKCoreKit.h file not found" error when trying to build for IOS.

> Ionic:
> 
>    Ionic CLI                     : 5.4.1 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework               : @ionic/angular 4.10.0
>    @angular-devkit/build-angular : 0.803.6
>    @angular-devkit/schematics    : 8.3.6
>    @angular/cli                  : 8.3.6
>    @ionic/angular-toolkit        : 2.0.0
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0
>    Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.0.1
>    Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 16 other plugins)
> 
> Utility:
> 
>    cordova-res : 0.6.0 
>    native-run  : 0.2.8 
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/Users/stephen/Library/Android/sdk)
>    ios-deploy        : 1.9.4
>    ios-sim           : 8.0.2
>    NodeJS            : v10.14.2 (/usr/local/bin/node)
>    npm               : 6.11.3
>    OS                : macOS Mojave
>    Xcode             : Xcode 11.0 Build version 11A420a

**Comment by mathatan** [comment]
I also have this issue with XCode 10, Cocoapods 1.7.5, Cordova 9.0.0, cordova-ios 5.0.1 and cordova-plugin-facebook4 6.0.0

The build works just fine when I run `cordova build ios` but if I try to build the project through xcode it'll fail for not finding the FB SDK files. If I had to guess it's something to do with the cordova build being more specific on where to search for the libs or alternatively the cordova build copies some files not otherwise available for the build? 

Maybe there's some magic happening within `BUILD TARGET FBSDKCoreKit OF PROJECT Pods WITH CONFIGURATION Debug` phase? (probably the release will have a different title)

**Comment by JayzeeHuang** [comment]
Getting same issue.

>Ionic:

   Ionic CLI                     : 5.4.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   Cordova CLI       : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms : android 7.1.4, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.0.0, (and 11 other plugins)

Utility:

   cordova-res : 0.5.2 (update available: 0.7.0)
   native-run  : 0.2.8 

System:

   ios-sim : 8.0.2
   NodeJS  : v10.15.0 (/usr/local/bin/node)
   npm     : 6.11.3
   OS      : macOS Mojave
   Xcode   : Xcode 11.0 Build version 11A420a

**Comment by hellkith** [comment]
Can you both try to delete and download the pods master repo?
I noticed the other day that my build was failing due to not having my repo up 2 date.

**Comment by bytenik** [comment]
In my case, I was on pod 1.8.1. Pod 1.8+ does not have a master repo, but rather uses a CDN. However it  seems like this plugin is incompatible with any Pod version >1.8, so I had to downgrade my system pod to 1.7.5.

**Comment by peterpeterparker** [comment]
Solution provided by @ljudbane has been documented in the iOS installation readme (see PR https://github.com/jeduan/cordova-plugin-facebook4/pull/810), therefore I close this issue.

**Comment by SteveKennedy** [comment]
The solution only works if you use Cordova iOS < 5. This is absolutely still an issue for newer versions.

**Comment by peterpeterparker** [comment]
@SteveKennedy tested and many users are using the plugin with Cordova iOS >= v5. if you do think that there is a bug, open and document a new issue and more important provide a sample repo and environment to reproduce the problem, thx in advance

**Comment by AliMonam** [comment]
I have the same issue. I find this one:
https://ionic.zendesk.com/hc/en-us/articles/360010049673-Managing-plugins-using-CocoaPods-in-Ionic-Appflow-
@SteveKennedy what do you think?

**Comment by danieldanielecki** [comment]
This is not an issue, the reason why you have it is due to missing in the section `Link Binary with Libraries` the following entries:
+ `FBSDKCoreKit.framework`
+ `FBSDKLoginKit.framework`
+ `FBSDKShareKit.framework`

Apparently even with `5.0.1` version of `cordova-ios` these 3 essential elements are **not** added automatically to these settings in Xcode. What it does however, in `project_name/platforms/ios/Pods` it creates these dependencies. What worked for me is to add the `Pods.xcodeproj` (by clicking `+` in `Link Binary with Libraries`) in your `Link Binary with Libraries` and then once again the `+` in `Link Binary with Libraries` and you should have 4 additional entries like on this image. Add `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework` and `FBSDKShareKit.framework`. Clean build folder and build again, should work - at least in my case it was the fix. Honestly speaking better documentation should be for this.

Note: Pods by default add only the `project_name_CashNinja.framework`, which does **not** work, you need to manually add these 3 essential FB SDK dependencies.

<img width="323" alt="Screenshot 2019-10-16 at 21 30 16" src="https://user-images.githubusercontent.com/12736263/66952169-5da0fd80-f05c-11e9-8925-85bb8276a5fe.png">


My `Podfile`

```
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'CashNinja' do
	project 'CashNinja.xcodeproj'
	pod 'FBSDKCoreKit', '5.7.0'
	pod 'FBSDKLoginKit', '5.7.0'
	pod 'FBSDKShareKit', '5.7.0'
end

```

Working on `Xcode` version `11.1` (build version `11A1027`), `pod` version `1.7.5`, `cordova-plugin-facebook4` version `6.2.0`, the rest versions you can find above.

**Comment by ejerskov** [comment]
@danieldanielecki 
I have done exactly like you but I still get the following error:

> Lexical or Preprocessor Issue Group
> /Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.h:13:9: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found

I've also cleaned the build before rebuilding again.
Any clues on what I should try next?

**Comment by Bruplanet** [comment]
I experienced this same issue and tried all the suggested solutions to no avail. Eventually I realised that permissions might be at the heart of it. I was running all my Phonegap / Cordova CLI commands as root (via sudo) because I originally installed Node and Phonegap as root. I uninstalled everything, then reinstalled it all but this time as my local user (which involved changing write access to a few files along the way). Once I had an environment in which I could run the Phonegap / Cordova CLI commands as my local user, everything worked cleanly.

**Comment by AlejandroDerbez** [comment]
> I experienced this same issue and tried all the suggested solutions to no avail. Eventually I realised that permissions might be at the heart of it. I was running all my Phonegap / Cordova CLI commands as root (via sudo) because I originally installed Node and Phonegap as root. I uninstalled everything, then reinstalled it all but this time as my local user (which involved changing write access to a few files along the way). Once I had an environment in which I could run the Phonegap / Cordova CLI commands as my local user, everything worked cleanly.

I had this problem too. I reinstalled Node and Cordova without sudo. And now it works. Thank you @danieldanielecki  and @Bruplanet for your response! Helped me a lot!!!! 

Now a little reminder for others: After cordova add ios, check the podfile and add this(any version) if missing:
pod 'FBSDKCoreKit', '5.7.0'
pod 'FBSDKLoginKit', '5.7.0'
pod 'FBSDKShareKit', '5.7.0'

It's better that you delete the pod folder, the podfile.lock file and run again pod install. If you have any doubts, I can help you, This took me a lot of days of research.

**Comment by arielhasidim** [comment]
Also experiencing this for a frustrating week now.
tried:

1. npm i -g npm
2. removed pods folder and lock
3. removed the facebook plugin
4. added plugin back

I got:
```
Installing "cordova-plugin-facebook4" for ios
Running command: pod install --verbose

[!] The `איפה דפי? [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-איפה דפי?/Pods-איפה דפי?.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `איפה דפי? [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-איפה דפי?/Pods-איפה דפי?.release.xcconfig'. This can lead to problems with the CocoaPods installation
```

pods.profile DOES contain:
```
pod 'FBSDKCoreKit', '5.7.0'
pod 'FBSDKLoginKit', '5.7.0'
pod 'FBSDKShareKit', '5.7.0'
```

Any help?

**Comment by lsantaniello** [comment]
I have similar issue :(

/Volumes/Data/projects/ionic3/my-app/platforms/ios/One To One/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.h:13:9: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found

```
Ionic:

   ionic (Ionic CLI)  : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 7 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/lsantaniello/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v7.7.0 (/usr/local/bin/node)
   npm               : 4.1.2
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```

Podfile:

```
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'One To One' do
	project 'One To One.xcodeproj'
	pod 'OneSignal', '2.11.2'
	pod 'FBSDKCoreKit', '~> 4.9'
	pod 'FBSDKLoginKit', '~> 4.9'
end
```

Please help me. I tring several solutions but the issue is not fixed

Thanks

**Comment by lsantaniello** [comment]
> pod 'FBSDKCoreKit', '5.7.0'
> pod 'FBSDKLoginKit', '5.7.0'
> pod 'FBSDKShareKit', '5.7.0'

could you please help me? Have you alternative contact please?

**Comment by AlejandroDerbez** [comment]
Hi Luca!! sorry for the late response, I was out of my country :D sure..
let me check.
Ok, first thing first.
Can you input cordova's commands in the terminal without sudo?

**Comment by arielhasidim** [comment]
> Hi Luca!! sorry for the late response, I was out of my country :D sure.. let me check. Ok, first thing first. Can you input cordova's commands in the terminal without sudo? El sáb., 16 nov. 2019 a las 16:21, Luca (<notifications@github.com>) escribió:
> […](#)

I'm also still struggling (4 replies above)!
I'm running Cordova commands without sudo.

**Comment by pipoa** [comment]
FYR.
I am an old version(4.0) user, I have to 
```
1.) complete remove plugin with param  --variable APP_ID="xxx" --variable APP_NAME="myprog"
2.) remove platform ios
    $ cordova  platform remove ios
3.) Install "CocoaPods dependency manager" which old version users may directly ignore this
     [https://github.com/jeduan/cordova-plugin-facebook4/tree/master/docs/ios#cocoapods](https://github.com/jeduan/cordova-plugin-facebook4/tree/master/docs/ios#cocoapods)
     $ sudo gem install cocoapods-dependencies
4.) add ios  back
    $ cordova platform add ios
5. ) install plugin back
   $ ionic cordova plugin add cordova-plugin-facebook4@latest --variable APP_ID="xxx" --variable APP_NAME="myprog"
```
finally
`** BUILD SUCCEEDED **`

**Comment by pipoa** [comment]
I finally figure out the root cause of this problem.
1. When I install plugin, I got errors below:
` 
The "myapp [Debug]" target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in "Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig". This can lead to problems with the CocoaPods installation
    - Use the $(inherited) flag, or
    - Remove the build settings from the target.
`

**It's the bug when there are multiple plugins that use pods at the same time, the search path is somehow messed up**

2. So I remove "cordova-plugin-facebook4" plugin first
3. According to the above cocoa message, I open xcode 
    XCode > Targets(myapp) > Build Settings > search "runpath" > double click "Runpath Search Paths" > REMOVE the orgin parameter and add '$(inherited)'  (or you can clean? CocoaPods 2nd 
 recommended msg)
4. Reinstall "cordova-plugin-facebook4"
   now, path conflict problem gone!
5. build your codova with `** BUILD SUCCEEDED **`

Note: If you get 'ld: framework not found Pods____' error (that was caused by your 1st add fb4 plugin ) when you build your platform, you can get rid of it by just remove 
 XCode > Targets(myapp) > General > scroll down to the bottom > remove the invalid "Pods____.framework"

**Comment by peterpeterparker** [comment]
cool to hear you found something. could you add your solution to the documentation and provide a PR @pipoa ?

**Comment by chrisluo** [comment]
I had the same problem. I was able to open and run it in Xcode with the myapp.xcworkspace file under platforms/ios. The myapp.xcodeproj file does not work with pods.

**Comment by arielhasidim** [comment]
> I finally figure out the root cause of this problem.
> 
> 1. When I install plugin, I got errors below:
>    `
>    The "myapp [Debug]" target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in "Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig". This can lead to problems with the CocoaPods installation
>    
>    * Use the $(inherited) flag, or
>    * Remove the build settings from the target.
>      `
> 
> **It's the bug when there are multiple plugins that use pods at the same time, the search path is somehow messed up**
> 
> 1. So I remove "cordova-plugin-facebook4" plugin first
> 2. According to the above cocoa message, I open xcode
>    XCode > Targets(myapp) > Build Settings > search "runpath" > double click "Runpath Search Paths" > REMOVE the orgin parameter and add '$(inherited)'  (or you can clean? CocoaPods 2nd
>    recommended msg)
> 3. Reinstall "cordova-plugin-facebook4"
>    now, path conflict problem gone!
> 4. build your codova with `** BUILD SUCCEEDED **`
> 
> Note: If you get 'ld: framework not found Pods____' error (that was caused by your 1st add fb4 plugin ) when you build your platform, you can get rid of it by just remove
> XCode > Targets(myapp) > General > scroll down to the bottom > remove the invalid "Pods____.framework"

After more then a month of struggling its finally works. not sure what made the difference, but I tried to recollect all of the steps, not sure about the order but:

1. I did as @pipoa suggested above (still didn't work)
2. removed and add the plugin (still didn't work)
3. tried to open "/platforms/ios/Pods/Pods.xproject", the pods file had red "failed" icon on Xcode.
4. updated all npm dependencies (still didn't work)
5. removed and add the plugin (still didn't work)
6. on platform/ios i ran: "pod 'FBSDKCoreKit'" + "pod 'FBSDKLoginKit'" + "pod 'FBSDKShareKit'"
7. on platform/ios i ran: "pod repo update" + " pod install"
8. now pods file opens just fine on Xcode and Cordova succeed with build
9. i always used xcworkspace file

**Comment by luigi37** [comment]
Thanks for the info above, anyway, for anyone else like me not familiar with pod I think the point 6 above:

> 6. On platform/ios i ran: "pod 'FBSDKCoreKit'" + "pod 'FBSDKLoginKit'" + "pod 'FBSDKShareKit'"

Should be better explained.
6. cd to folder "platforms/ios" inside your cordova project, open with a text editor the file "Podfile" and at the bottom of it add the 3 lines
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

7. inside folder "platforms/ios" run "pod repo update" and the "pod install"

**Comment by arielhasidim** [comment]
> Thanks for the info above, anyway, for anyone else like me not familiar with pod I think the point 6 above:
> 
> > 1. On platform/ios i ran: "pod 'FBSDKCoreKit'" + "pod 'FBSDKLoginKit'" + "pod 'FBSDKShareKit'"
> 
> Should be better explained.
> 6. cd to folder "platforms/ios" inside your cordova project, open with a text editor the file "Podfile" and at the bottom of it add the 3 lines
> 
> ```
> pod 'FBSDKCoreKit'
> pod 'FBSDKLoginKit'
> pod 'FBSDKShareKit'
> ```
> 
> 1. inside folder "platforms/ios" run "pod repo update" and the "pod install"

I actually meant that I ran it in terminal. These lines already existed in the file beforehand.
I edited my answer, thanks.

**Comment by carolinemcq** [comment]
I've tried all of the advice in this thread and I still can't get this plugin to work. Using version 6.4.0

**Comment by arielhasidim** [comment]
> I've tried all of the advice in this thread and I still can't get this plugin to work. Using version 6.4.0
> 
> From what I can tell from this thread, there seems to be steps missing from the documentation on how to actually install this plugin? It's not as straightforward as one might think.

as someone that also struggle with it for two months - i dont know what was the step the fixed it, but i encourage you to keep and try.
i dont think its a problem with the instructions, its somthing with the change to cocoapods, something is clashing overthere.

**Comment by felipeclopes** [comment]
There is something with the repo, since it was supposed to work straight from the build command. I'm troubleshooting my project, since I'm facing the same issue as you guys.

```
"cordova-ios": "^5.1.1",
```
```
$ ionic info

Ionic:

   Ionic CLI                     : 6.1.0 (/Users/felipeclopes/.nvm/versions/node/v12.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.5, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.13.0 (/Users/felipeclopes/.nvm/versions/node/v12.13.0/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.4 Build version 11E146
```

```
> cordova plugin ls
branch-cordova-sdk 4.1.2 "branch-cordova-sdk"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-firebasex 8.1.1 "Google Firebase Plugin"
cordova-plugin-health 1.1.3 "Cordova Health"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic 5.4.5 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-purchases 1.0.5 "Purchases"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Comment by ishaiavrahami** [comment]
I have almost the same config as @felipeclopes and its also not building. However whenever i run an older version such as 5.0.0 it build but when I login it throws an error of "Error: User Cancelled", so i figured i needed to update my version to 6.4.0. That didnt help because now it wont build at all.

**Comment by kodeine** [comment]
@ishaiavrahami @felipeclopes same here same plugin version installed

**Comment by felipeclopes** [comment]
I was able to build going to platforms/ios folder and running

```
pod repo update
pod install
```

Then the build on Xcode worked

**Comment by ishaiavrahami** [comment]
I got it working. Just removed platform IOS and built again. Works amazing.

**Comment by carolinemcq** [comment]
It's still not working on my project.

I tried to run `pod repo update` but I got this error message: `unable to
execute /usr/local/bin/pod: No such file or directory`

Next, I removed the iOS platform and built it again and I got the
same error all over again.

**Comment by Akolbogr** [comment]
Hey guys, I cannot get past this error in 2 days now. Have tried all suggestions in this thread.  

The following build commands failed:
	CompileC /var/root/Library/Developer/Xcode/DerivedData/abcd/Objects-normal/x86_64/FacebookConnectPlugin.o 
/Users/abcd/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
xcodebuild: Command failed with exit code 65

Here is my ionic info result:
Ionic:

   Ionic CLI          : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 20 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-sim : 8.0.2
   NodeJS  : v12.16.2 (/usr/local/bin/node)
   npm     : 6.14.4
   OS      : macOS Catalina
   Xcode   : Xcode 11.4.1 Build version 11E503a

**Comment by andevit** [comment]
> If you absolutely must use cordova ios < 5 the you can add the following lines to plugins/cordova-plugin-facebook4/plugin.xml inside `<platform name="ios">`:
> 
> ```
>     <framework src="FBSDKCoreKit" type="podspec" spec="5.2.3" />
>     <framework src="FBSDKLoginKit" type="podspec" spec="5.2.3" />
>     <framework src="FBSDKShareKit" type="podspec" spec="5.2.3" />
> ```
> 
> This will add the entries to ios platform's Podfile (after removing and adding platform). Tested on cordova 6.5 and cordova_ios 4.5.5.

@ljudbane sorry but I have been trying for 3 days but I can't solve it. 

I have this situation:

```
Ionic:

   Ionic CLI          : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 6.4.0, **ios 4.5.4**
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.5.0, (and 26 other plugins)
```

I followed your suggestion but if i run ionic "cordova build ios", it output this error:

> /xxxxxxxxxxx/platforms/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:21:9: fatal error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
> #import <FBSDKCoreKit/FBSDKCoreKit.h>

Your help would be greatly appreciated

**Comment by ljudbane** [comment]
@andevit Have you tried building it with xcode? I gave up on 'cordova build ios' a while ago, because it never builds properly anymore. I blame a combination of old cordova version and new xcode. Anyhow, i now always build for ios with xcode.

'cordova prepare ios' will copy ionic code to the ios project, then i continue in xcode.

**Comment by andevit** [comment]
@ljudbane sorry for the stupid question. How do you do it? 

I have always used this command:
`ionic cordova build ios --prod`

**Comment by ljudbane** [comment]
@andevit When you run that command, it will build the ios project (with xcode command line tools). But then if you wanna run it on simulator for instance, you still have to open xcode and run it from there. 
What i meant was, that if command-line build fails, you can try to do the same and run it on simulator. The xcode will then build the project again. And maybe this time there won't be an error.
At least that's what happens in my case.

As i'm not familiar with your workflow, what do you do after 'ionic cordova build ios --prod'?

**Comment by andevit** [comment]
@ljudbane it works fine! thank you very much!
